import 'package:tesis_app/infraestructure/models/medicines/medicine_model.dart';

const itemsMedicineConstant = <MedicineModel>[
  MedicineModel(
      id: "",
      nombre: "Amoxicilina",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Clorfenamina",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Paracetamol",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Ibuprofeno",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Aspirina",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Simvastatina",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Omeprazol",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Levotiroxina",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Ramipril",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Amlodipíno",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Atorvastatina",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
  MedicineModel(
      id: "",
      nombre: "Ventolin",
      cantidadMedicamentos: "1",
      horaInicio: "08:00",
      horaIntermedio: "14:00",
      horaFin: "20:00"),
];
